/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/auth-api';
export * from './api/clubs-api';
export * from './api/comments-api';
export * from './api/events-api';
export * from './api/institutes-api';
export * from './api/posts-api';
export * from './api/reactions-api';
export * from './api/user-api';
export * from './api/users-api';

