/* tslint:disable */
/* eslint-disable */
/**
 * StudHub API [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClubDetailDTO
 */
export interface ClubDetailDTO {
    /**
     * 
     * @type {number}
     * @memberof ClubDetailDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ClubDetailDTO
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ClubDetailDTO
     */
    'subscriberCount': number;
    /**
     * 
     * @type {boolean}
     * @memberof ClubDetailDTO
     */
    'isUserSubscribed': boolean;
    /**
     * 
     * @type {string}
     * @memberof ClubDetailDTO
     */
    'about'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClubDetailDTO
     */
    'imageUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClubDetailDTO
     */
    'bannerUrl'?: string | null;
}

