/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PersonSummaryDTO } from './person-summary-dto';

/**
 * 
 * @export
 * @interface CommentDetailDTO
 */
export interface CommentDetailDTO {
    /**
     * 
     * @type {number}
     * @memberof CommentDetailDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CommentDetailDTO
     */
    'content': string;
    /**
     * 
     * @type {PersonSummaryDTO}
     * @memberof CommentDetailDTO
     */
    'personSummaryDTO': PersonSummaryDTO;
    /**
     * 
     * @type {number}
     * @memberof CommentDetailDTO
     */
    'inReplyTo'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CommentDetailDTO
     */
    'threadId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CommentDetailDTO
     */
    'replyCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentDetailDTO
     */
    'postId': number;
    /**
     * 
     * @type {string}
     * @memberof CommentDetailDTO
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetailDTO
     */
    'deletedAt'?: string | null;
}

