/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventDetailDTO
 */
export interface EventDetailDTO {
    /**
     * 
     * @type {number}
     * @memberof EventDetailDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof EventDetailDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EventDetailDTO
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof EventDetailDTO
     */
    'location'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDetailDTO
     */
    'startTime': string;
    /**
     * 
     * @type {string}
     * @memberof EventDetailDTO
     */
    'createdAt': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventDetailDTO
     */
    'eventImages': Array<string>;
}

