/* tslint:disable */
/* eslint-disable */
/**
 * StudHub API [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventDTO
 */
export interface EventDTO {
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    'location'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    'startTime': string;
}

