/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PersonDetailDTOInstitute } from './person-detail-dtoinstitute';

/**
 * 
 * @export
 * @interface PersonDetailDTO
 */
export interface PersonDetailDTO {
    /**
     * 
     * @type {number}
     * @memberof PersonDetailDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PersonDetailDTO
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof PersonDetailDTO
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof PersonDetailDTO
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonDetailDTO
     */
    'birthDate': string;
    /**
     * 
     * @type {string}
     * @memberof PersonDetailDTO
     */
    'about'?: string | null;
    /**
     * 
     * @type {PersonDetailDTOInstitute}
     * @memberof PersonDetailDTO
     */
    'institute'?: PersonDetailDTOInstitute | null;
    /**
     * 
     * @type {number}
     * @memberof PersonDetailDTO
     */
    'roleId': number;
    /**
     * 
     * @type {number}
     * @memberof PersonDetailDTO
     */
    'activityStatusId': number;
    /**
     * 
     * @type {string}
     * @memberof PersonDetailDTO
     */
    'imagePath'?: string | null;
}

