/* tslint:disable */
/* eslint-disable */
/**
 * StudHub API [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClubDetailDTO } from './club-detail-dto';

/**
 * 
 * @export
 * @interface PostDetailDTO
 */
export interface PostDetailDTO {
    /**
     * 
     * @type {number}
     * @memberof PostDetailDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PostDetailDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PostDetailDTO
     */
    'content': string;
    /**
     * 
     * @type {number}
     * @memberof PostDetailDTO
     */
    'reactionCount': number;
    /**
     * 
     * @type {number}
     * @memberof PostDetailDTO
     */
    'commentCount': number;
    /**
     * 
     * @type {boolean}
     * @memberof PostDetailDTO
     */
    'isUserReacted': boolean;
    /**
     * 
     * @type {ClubDetailDTO}
     * @memberof PostDetailDTO
     */
    'club': ClubDetailDTO;
    /**
     * 
     * @type {Array<string>}
     * @memberof PostDetailDTO
     */
    'postImages': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PostDetailDTO
     */
    'createdAt': string;
}

