/* tslint:disable */
/* eslint-disable */
/**
 * StudHub API [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostDTO
 */
export interface PostDTO {
    /**
     * 
     * @type {string}
     * @memberof PostDTO
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PostDTO
     */
    'content': string;
    /**
     * 
     * @type {number}
     * @memberof PostDTO
     */
    'clubId': number;
}

