/* tslint:disable */
/* eslint-disable */
/**
 * StudHub API [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    'birthDate': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    'about'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RegisterDTO
     */
    'instituteId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterDTO
     */
    'password': string;
}

