/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonSummaryDTO
 */
export interface PersonSummaryDTO {
    /**
     * 
     * @type {number}
     * @memberof PersonSummaryDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PersonSummaryDTO
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof PersonSummaryDTO
     */
    'lastName': string;
    /**
     * 
     * @type {number}
     * @memberof PersonSummaryDTO
     */
    'instituteId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PersonSummaryDTO
     */
    'imagePath'?: string | null;
}

