import type { Metadata } from 'next';
import './globals.css';
import ProviderLayout from '@/components/Provider/Provider';

export const metadata: Metadata = {
    title: 'Setka',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ProviderLayout>{children}</ProviderLayout>
            </body>
        </html>
    );
}
