name: 'Test build'
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs:
    build:
        name: Test build
        runs-on: ubuntu-latest

        steps:
            - name: git-checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Generate OpenAPI client [production-api]
              run: bun run api:code-gen

            - name: Build application
              run: bun run build
