name: 'Deploy client on server'
on:
    workflow_run:
        workflows:
            - 'Test build'
        types:
            - completed

jobs:
    deploy:
        if: >-
            ${{
              github.event.workflow_run.conclusion == 'success' &&
              github.event.workflow_run.head_branch == 'main'
            }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_KEY }}
                  script: |
                      cd ${{ secrets.CLIENT_PATH }}
                      git pull origin main
                      cd ${{ secrets.CONF_PATH }}
                      docker compose up --build -d --force-recreate frontend
